### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by bruh420882** [0xkuj/WARemove999Limit#1]
why I can't download it

**Comment by 0xkuj** [comment]
How are you trying to download it?

**Comment by bruh420882** [comment]
on ios

**Comment by bruh420882** [comment]
idk how to

**Comment by 0xkuj** [comment]
You need to download the deb file from packages folder and install it via filza, or use your package manager (e.g cydia) and install it from my repo https://0xkuj.github.io/kujman/
You need to be jailbroken of course..
